[project]
name = "lerobot_robot_piper"
version = "0.1.0"
dependencies = [
    "lerobot>=0.4.0",
    "python-can",
    "piper_sdk"]


[project.urls]
Home = "https://github.com/forgetwhatwant/lerobot_robot_piper"

